For review
FeixiDev/Hydra pull request #69
Opened 2020-09-02 03:35 UTC by mattie-feng

2020-09-02 05:55 UTC, userhei requested changes
先提出来，我继续Review

2020-09-02 05:55 UTC, userhei commented on consts.py
> +    "replay时，输出日志中的异常信息后，此次replay事务也随之停止"
这是说解决了这个问题？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        consts.set_glo_tsc_id(f'{self.transaction_id}s')
这个后面的s？

2020-09-02 05:55 UTC, userhei commented on control.py
> +    def instantiation_class(self):
名词 对 名词？？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        self._host = h.HostTest()
h就简写了？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        id_list = s.change_id_range_to_list(args.id_range)
这个也太长了吧？id_str_to_list

2020-09-02 05:55 UTC, userhei commented on control.py
> +        for lun_id in consts.glo_id_list():
58年的努力，就为了66岁的一个回眸？？？

另外用空行来把不同类型的赋值间隔开来，也是常规做法吧？

2020-09-02 05:55 UTC, userhei commented on control.py
> +                self._host.io_test()
drbd：为什么，有人有5毛钱，而我没有。
host：我被种族隔离了？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        print(f'**** Start working for ID {num} ****'.center(format_width, '='))
既然是只有一个，就省了这一步吧。85行也省了

2020-09-02 05:55 UTC, userhei commented on control.py
> +            time.sleep(0.5)
其实都不需要间隔那么久的，可以把这个sleep放在每一个被调用函数的开始位置。不是有人崇尚极致简化吗？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        print(f'**** Start working for ID {num} ****'.center(format_width, '='))
85行不能省

2020-09-02 05:55 UTC, userhei commented on control.py
> +                    self._drbd.status_verify(f'res_{consts.glo_str()}_{consts.glo_id()}')
这里要这么别扭吗？不是把res_name通过变量传递过来了？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        random_number = args.random_number if args.random_number else 3
else capacity吧？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        random_number = args.random_number if args.random_number else 3
哦，这里是 random_number

2020-09-02 05:55 UTC, userhei commented on control.py
> +        format_width = 105 if consts.glo_rpl() == 'yes' else 80
如果都是这，这个可以设置在全局变量

2020-09-02 05:55 UTC, userhei commented on control.py
> +        random_number = args.random_number if args.random_number else 3
哦，不对，就是capacity

2020-09-02 05:55 UTC, userhei commented on control.py
> +            s.generate_iqn_list(args.capacity)
129 可以放在 132 里面吧

2020-09-02 05:55 UTC, userhei commented on control.py
> +                for iqn in s.host_random_iqn(random_number):
pick_iqn_random

2020-09-02 05:55 UTC, userhei commented on control.py
> +                for iqn in s.host_random_iqn(random_number):
加s

2020-09-02 05:55 UTC, userhei commented on control.py
> +            id_list = s.change_id_range_to_list(args.id_range)
这一步不应该是放在最最最开始执行的吗，省的每次都要写？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        self.update_attribute('str')
完全可以写在一行的，忍了很久了

2020-09-02 05:55 UTC, userhei commented on control.py
> +    def replay_parser(self):
叫个 set_replay_mode 多好呢？

2020-09-02 05:55 UTC, userhei commented on control.py
> +            consts.set_glo_tsc_id(tid)
很多时候通过传递参数就可以吧，为什么都要这么set一下

2020-09-02 05:55 UTC, userhei commented on control.py
> +        if args.tid:
不是应该确定是 tid模式，才会调用这方法吗，为什么这里还要if

2020-09-02 05:55 UTC, userhei commented on control.py
> +            self.run_rpl_tid(args, parser_obj)
这部分，不是用绑定函数方式实现了？

2020-09-02 05:55 UTC, userhei commented on control.py
> +        print('* MODE : REPLAY *')
这一句不应该是 rpl 最开始print的？

2020-09-02 05:55 UTC, userhei commented on debug_log.py
> +    os.mkdir(local_debug_folder)
就不改，就不改，打死也不改

2020-09-02 07:15 UTC, userhei requested changes
四五十个 review，后面也是没那么精神集中了。。。总体来说，里面的调用和设计还是有很大出入，当然主要是设计部分并没有考虑足够周全。。。这种情况，应该是先基于实际需求，把设计部分丰满之后，然后根据设计组合代码；而不是沿着原来的逻辑，就这么地。。。那我们优化设计有什么意义？？

2020-09-02 07:15 UTC, userhei commented on sundry.py
> +def ex_telnet_cmd(telnet_obj, unique_str, cmd, oprt_id):
咦。。。这里来个ex

2020-09-02 07:15 UTC, userhei commented on sundry.py
> +            raise consts.ReplayExit
参考下 Zane提到的建议

2020-09-02 07:15 UTC, userhei commented on sundry.py
> +    def get_disk_dev(self, dev_vendor):
这俩，是内部的吧

2020-09-02 07:15 UTC, userhei commented on sundry.py
> +        self.tgt_ip=tgt_ip
有个change iqn 的东西，也应该放在这个类里面

2020-09-02 07:15 UTC, userhei commented on vplx.py
> +        gnd = s.GetNewDisk(SSH, NETAPP_IP)
gnd？？

2020-09-02 07:15 UTC, userhei commented on vplx.py
> +        blk_dev_name = gnd.get_disk_from_netapp()
blk_dev_name = GetNewDisk(SSH, NETAPP_IP).get_disk_from_netapp()

实在是懒得话，这样更懒一些，并且更清晰一些。

2020-09-02 07:15 UTC, userhei commented on vplx.py
> +        self._crm_and_targetcli_verify(lu_name)
就是这部分，完全不需要写在这里，和Host类似。 类外调用s.x

2020-09-02 07:15 UTC, userhei commented on vplx.py
> +        s.scsi_rescan(SSH, 'r')
这一句话的函数，不用写哇，你调用时候直接 s.X，然后注释写过去不就行了。。。这个设计图里不是已经专门删除掉了吗？

2020-09-02 09:40 UTC, mattie-feng reviewed
还有一些Info log没有记录

2020-09-02 09:40 UTC, mattie-feng commented on control.py
> +                print(f'{"":-^{format_width}}', '\n')
同放到io_test后，或者只在最末尾输出

2020-09-02 09:40 UTC, mattie-feng commented on control.py
> +                    print(f'{"":-^{format_width}}', '\n')
同放末尾

2020-09-02 09:40 UTC, mattie-feng commented on control.py
> +                s.pwl('Start to remove all deleted disk device on netapp vplx host', 0)
netapp / vplx / host

2020-09-02 09:40 UTC, mattie-feng commented on control.py
> +                print(f'{"":-^80}', '\n')
print(f'{"":-^{format_width}}', '\n')

2020-09-02 09:40 UTC, mattie-feng commented on control.py
> +            print(f'事务:{consts.glo_tsc_id()} 不满足replay条件，所执行的命令为：python main.py {via_cmd_dict["cmd"]}')
via_cmd_dict['valid'] 为T 或者F会不会更好看
if via_cmd_dict['valid'] == '1'时还会有不满足replay条件的情况吗？

2020-09-02 09:40 UTC, mattie-feng commented on debug_log.py
> +    s.prt(f'All debug log stor in folder localhost {local_debug_folder}')
s.prt(f'All debug log stored in localfolder {local_debug_folder}')

2020-09-02 09:40 UTC, mattie-feng commented on host_initiator.py
> +    def host_rescan_r(self):
删

2020-09-02 09:40 UTC, mattie-feng commented on main.py
> +            help='Output current hydra version'
Show current version

2020-09-02 09:40 UTC, mattie-feng commented on main.py
> +            help='Replay all'
Replay all recorded transactions

2020-09-02 09:40 UTC, mattie-feng commented on vplx.py
> +        if down_result['sts']:
handle_exception

2020-09-02 09:40 UTC, mattie-feng commented on vplx.py
> +        if del_result['sts']:
handle_exception

2020-09-02 09:40 UTC, mattie-feng commented on vplx.py
> +        if show_result['sts']:
handle_exception

2020-09-02 09:40 UTC, mattie-feng commented on sundry.py
> +NETAPP_IP = '10.203.1.231'
删 NETAPP_IP

2020-09-02 09:40 UTC, mattie-feng commented on vplx.py
> +            s.pwe('Failed in verify the allow initiator', 2, 2)
Failed to modify the allowed initiator

2020-09-02 09:40 UTC, mattie-feng commented on vplx.py
> +    def _modify_allow_initiator(self, lu_name):
pwl:Start to modify_allow_initiator

2020-09-03 02:38 UTC, Ethan009 commented on control.py
> +        random_number = args.random_number if args.random_number else 3
random_number = args.random_number if args.capacity>args.random_number else args.capacity

2020-09-03 02:58 UTC, Ethan009 commented on control.py
> +        format_width = 105 if consts.glo_rpl() == 'yes' else 80
我觉得如果只是这几个函数用到，代码这么简单的情况下不太需要设置全局变量

2020-09-03 05:30 UTC, Ethan009 commented on control.py
> +            consts.set_glo_tsc_id(tid)
这里其实是有逻辑在这里，比较复杂，但优化后，已经修改了

2020-09-03 08:51 UTC, Ethan009 commented on control.py
> +        if args.tid:
已改

2020-09-07 00:23 UTC, Ethan009 commented on control.py
> +            id_list = s.change_id_range_to_list(args.id_range)
最开始初始化stor、drbd类，建立ssh链接

2020-09-07 00:41 UTC, Ethan009 commented on vplx.py
> +        s.scsi_rescan(SSH, 'r')
这个函数，主要需要ssh对象，并且是在control调用的，还需要判断是否是rpl，我觉得这个方法目前来说比较好

2020-09-09 03:37 UTC, closed without merging